spring:
  jackson:
   deserialization:
    fail-on-unknown-properties : true

  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
        format_sql: true

logging:
  level:
    org:
      springframework.security: DEBUG
      hibernate.SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE

my-app:
  password: password
  admin-username: admin@email.com
  user-username: user
  client-id: clientId
  client-secret: clientPassword